name: Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Triggers only on tags like v1.0.0, v2.1.3, etc
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and deploy
      run: echo "Deploying version ${GITHUB_REF_NAME}"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Sanitize Tag Name
      id: tag
      run: |
        TAG=$(echo ${GITHUB_REF_NAME} | sed 's/[^a-zA-Z0-9_.-]/-/g')
        echo "Sanitized Tag: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: antonimoragues/prova:${{ env.TAG }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: antonimoragues/prova:${GITHUB_REF_NAME}
